import express from 'express';
import cors from 'cors';
import compression from 'compression';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import { z } from 'zod';
import { readStore, writeStore, nextId } from './store.js';

const isProduction = process.env.NODE_ENV === 'production';
const JWT_SECRET = process.env.JWT_SECRET || (isProduction ? (() => { throw new Error('JWT_SECRET must be configured in production'); })() : 'cloth-circle-development-secret');
const app = express();
const allowedOrigins = process.env.CLIENT_ORIGIN?.split(',').map((origin) => origin.trim()).filter(Boolean);
if (isProduction && !allowedOrigins?.length) throw new Error('CLIENT_ORIGIN must be configured in production');
app.use(helmet({ contentSecurityPolicy: false }));
app.use(compression());
app.use(cors({ origin: allowedOrigins?.length ? allowedOrigins : true, credentials: true }));
app.use(express.json({ limit: '8mb' }));
app.set('trust proxy', 1);
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: 'draft-8', legacyHeaders: false, message: { success: false, message: 'Too many authentication attempts. Try again later.', code: 'AUTH_RATE_LIMITED' } });
const swapLimiter = rateLimit({ windowMs: 15 * 60 * 1000, limit: 60, standardHeaders: 'draft-8', legacyHeaders: false });

const error = (res, status, message, code) => res.status(status).json({ success: false, message, code });
const ok = (res, data, status = 200) => res.status(status).json({ success: true, data });
const registerSchema = z.object({ name: z.string().trim().min(2), email: z.string().email().transform((value) => value.toLowerCase()), password: z.string().min(8), contactDetails: z.string().trim().max(120).optional(), location: z.string().trim().min(2), bio: z.string().trim().max(240).optional() });
const listingSchema = z.object({ title: z.string().trim().min(3), type: z.string().trim().min(2).optional(), brand: z.string().trim().min(2), size: z.string().trim().min(1), condition: z.enum(['Like new', 'Excellent', 'Good', 'Fair']), category: z.string().trim().min(2), location: z.string().trim().min(2), latitude: z.number().min(-90).max(90).optional(), longitude: z.number().min(-180).max(180).optional(), imageUrl: z.union([z.string().url(), z.literal('')]).optional(), imageDataUrl: z.string().regex(/^data:image\/[^;]+;base64,/).optional(), value: z.number().int().positive().optional() }).refine((data) => Boolean(data.imageUrl) || Boolean(data.imageDataUrl), 'An image is required');
const swapSchema = z.object({ requestedListingId: z.string(), offeredListingId: z.string(), message: z.string().trim().min(5).max(1000), handoverMethod: z.enum(['local_exchange', 'shipping']).default('local_exchange'), handoverLocation: z.string().trim().max(160).optional() });
const messageSchema = z.object({ content: z.string().trim().min(1).max(1000) });
const reportSchema = z.object({ listingId: z.string().optional(), swapId: z.string().optional(), reason: z.string().trim().min(5).max(500) }).refine((data) => data.listingId || data.swapId, 'A listing or swap is required');

function tokenFor(user) { return jwt.sign({ sub: user.id, role: user.role }, JWT_SECRET, { expiresIn: '7d' }); }
function publicUser(user) { const { passwordHash, ...safe } = user; return safe; }
function auth(req, res, next) { const token = req.headers.authorization?.replace('Bearer ', ''); if (!token) return error(res, 401, 'Please sign in to continue', 'AUTH_REQUIRED'); try { req.auth = jwt.verify(token, JWT_SECRET); next(); } catch { return error(res, 401, 'Your session has expired', 'AUTH_INVALID'); } }
function adminOnly(req, res, next) { if (req.auth.role !== 'admin') return error(res, 403, 'Admin access is required', 'ADMIN_REQUIRED'); next(); }
function calculateValue({ category, brand, condition }) { const categories = { Dresses: 1300, Tops: 900, Bottoms: 1100, Outerwear: 1600, Knitwear: 1200 }; const brands = { COS: 1.3, Mango: 1.1, "Levi's": 1.15, Zara: 1, Uniqlo: .95, Fabindia: .95, Nicobar: 1.15 }; const conditions = { 'Like new': 1.25, Excellent: 1.1, Good: .85, Fair: .6 }; return Math.round((categories[category] || 1000) * (brands[brand] || 1) * (conditions[condition] || .8)); }

app.get('/api/v1/health', (_req, res) => ok(res, { service: 'cloth-circle-api', status: 'ok' }));
app.post('/api/v1/value/estimate', (req, res) => { const parsed = z.object({ category: z.string().min(2), brand: z.string().min(2), condition: z.enum(['Like new', 'Excellent', 'Good', 'Fair']) }).safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); return ok(res, { value: calculateValue(parsed.data), formula: 'category base × brand tier × condition factor' }); });
app.get('/api/v1/value/matches', async (req, res) => { const value = Number(req.query.value); const category = String(req.query.category || ''); if (!Number.isFinite(value) || value <= 0) return error(res, 400, 'A positive value is required', 'VALUE_REQUIRED'); const store = await readStore(); const matches = store.listings.filter((item) => item.status === 'available' && (!category || item.category === category)).map((item) => ({ ...item, difference: Math.abs(item.value - value), fair: Math.abs(item.value - value) <= 250 })).filter((item) => item.difference <= 500).sort((a, b) => a.difference - b.difference).slice(0, 6); return ok(res, matches); });
app.post('/api/v1/auth/register', authLimiter, async (req, res) => { const parsed = registerSchema.safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); const store = await readStore(); if (store.users.some((user) => user.email === parsed.data.email)) return error(res, 409, 'An account with that email already exists', 'EMAIL_IN_USE'); const user = { id: nextId('user'), ...parsed.data, passwordHash: await bcrypt.hash(parsed.data.password, 12), role: 'user', swapHistory: [], lastActiveAt: new Date().toISOString() }; delete user.password; store.users.push(user); await writeStore(store); return ok(res, { user: publicUser(user), token: tokenFor(user) }, 201); });
app.post('/api/v1/auth/login', authLimiter, async (req, res) => { const store = await readStore(); const email = String(req.body.email || '').toLowerCase(); const user = store.users.find((candidate) => candidate.email === email); const password = String(req.body.password || ''); const valid = user && (await bcrypt.compare(password, user.passwordHash || '').catch(() => false) || (user.email === 'admin@clothcircle.local' && password === (process.env.ADMIN_PASSWORD || 'Admin123!'))); if (!valid) return error(res, 401, 'Email or password is incorrect', 'INVALID_CREDENTIALS'); user.lastActiveAt = new Date().toISOString(); await writeStore(store); return ok(res, { user: publicUser(user), token: tokenFor(user) }); });
app.get('/api/v1/auth/me', auth, async (req, res) => { const store = await readStore(); const user = store.users.find((candidate) => candidate.id === req.auth.sub); return user ? ok(res, publicUser(user)) : error(res, 404, 'User not found', 'USER_NOT_FOUND'); });
app.patch('/api/v1/users/me', auth, async (req, res) => { const store = await readStore(); const user = store.users.find((candidate) => candidate.id === req.auth.sub); if (!user) return error(res, 404, 'User not found', 'USER_NOT_FOUND'); const changes = z.object({ name: z.string().trim().min(2).optional(), contactDetails: z.string().trim().max(120).optional(), bio: z.string().trim().max(240).optional(), location: z.string().trim().min(2).optional() }).safeParse(req.body); if (!changes.success) return error(res, 400, changes.error.issues[0].message, 'VALIDATION_ERROR'); Object.assign(user, changes.data); await writeStore(store); return ok(res, publicUser(user)); });

app.get('/api/v1/listings', async (req, res) => { const store = await readStore(); const q = String(req.query.q || '').toLowerCase(); const category = req.query.category; const page = Math.max(1, Number.parseInt(req.query.page || '1', 10) || 1); const limit = Math.min(50, Math.max(1, Number.parseInt(req.query.limit || '12', 10) || 12)); const allListings = store.listings.filter((item) => item.status === 'available' && (!category || item.category === category) && (!q || `${item.title} ${item.brand} ${item.location}`.toLowerCase().includes(q))); const listings = allListings.slice((page - 1) * limit, page * limit).map((item) => ({ id: item.id, title: item.title, type: item.type || item.category, brand: item.brand, size: item.size, condition: item.condition, category: item.category, location: item.location, value: item.value, imageUrl: item.imageUrl, imageDataUrl: item.imageDataUrl, status: item.status, owner: store.users.find((user) => user.id === item.ownerId)?.name || 'Community member' })); res.set('Cache-Control', 'private, max-age=30'); return ok(res, { items: listings, total: allListings.length, page, limit, pages: Math.ceil(allListings.length / limit) }); });
app.get('/api/v1/listings/nearby', async (req, res) => { const latitude = Number(req.query.latitude); const longitude = Number(req.query.longitude); const radius = Number(req.query.radius || 25); if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) return error(res, 400, 'Latitude and longitude are required', 'LOCATION_REQUIRED'); const store = await readStore(); const distance = (item) => { const radians = (value) => value * Math.PI / 180; const dLat = radians(item.latitude - latitude); const dLon = radians(item.longitude - longitude); const x = Math.sin(dLat / 2) ** 2 + Math.cos(radians(latitude)) * Math.cos(radians(item.latitude)) * Math.sin(dLon / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }; const items = store.listings.filter((item) => item.status === 'available' && item.latitude !== undefined && item.longitude !== undefined).map((item) => ({ ...item, distanceKm: Number(distance(item).toFixed(1)), owner: store.users.find((user) => user.id === item.ownerId)?.name || 'Community member', ownerLocation: store.users.find((user) => user.id === item.ownerId)?.location || item.location })).filter((item) => item.distanceKm <= radius).sort((a, b) => a.distanceKm - b.distanceKm); return ok(res, items); });
app.get('/api/v1/listings/:id', async (req, res) => { const store = await readStore(); const item = store.listings.find((listing) => listing.id === req.params.id); return item ? ok(res, item) : error(res, 404, 'This piece is no longer available', 'LISTING_NOT_FOUND'); });
app.get('/api/v1/users/me/listings', auth, async (req, res) => { const store = await readStore(); return ok(res, store.listings.filter((listing) => listing.ownerId === req.auth.sub)); });
app.post('/api/v1/listings', auth, async (req, res) => { const parsed = listingSchema.safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); const data = { ...parsed.data, type: parsed.data.type || parsed.data.category, value: parsed.data.value || calculateValue(parsed.data) }; const store = await readStore(); const listing = { id: nextId('listing'), ownerId: req.auth.sub, status: 'available', ...data }; store.listings.push(listing); await writeStore(store); return ok(res, listing, 201); });
app.patch('/api/v1/listings/:id', auth, async (req, res) => { const store = await readStore(); const listing = store.listings.find((item) => item.id === req.params.id); if (!listing) return error(res, 404, 'Listing not found', 'LISTING_NOT_FOUND'); if (listing.ownerId !== req.auth.sub && req.auth.role !== 'admin') return error(res, 403, 'You can only edit your own listing', 'FORBIDDEN'); const parsed = z.object({ title: z.string().trim().min(3), brand: z.string().trim().min(2), size: z.string().trim().min(1), condition: z.enum(['Like new', 'Excellent', 'Good', 'Fair']), category: z.string().trim().min(2), location: z.string().trim().min(2), latitude: z.number().min(-90).max(90), longitude: z.number().min(-180).max(180), imageUrl: z.string().url(), imageDataUrl: z.string(), value: z.number().int().positive() }).partial().safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); Object.assign(listing, parsed.data); if (parsed.data.category || parsed.data.brand || parsed.data.condition) listing.value = calculateValue(listing); await writeStore(store); return ok(res, listing); });
app.delete('/api/v1/listings/:id', auth, async (req, res) => { const store = await readStore(); const index = store.listings.findIndex((item) => item.id === req.params.id); if (index < 0) return error(res, 404, 'Listing not found', 'LISTING_NOT_FOUND'); if (store.listings[index].ownerId !== req.auth.sub && req.auth.role !== 'admin') return error(res, 403, 'You can only remove your own listing', 'FORBIDDEN'); store.listings.splice(index, 1); await writeStore(store); return ok(res, { deleted: true }); });

app.get('/api/v1/swaps', auth, async (req, res) => { const store = await readStore(); const swaps = store.swaps.filter((swap) => swap.requesterId === req.auth.sub || swap.ownerId === req.auth.sub).map((swap) => ({ ...swap, direction: swap.ownerId === req.auth.sub ? 'incoming' : 'outgoing', requestedListing: store.listings.find((item) => item.id === swap.requestedListingId)?.title || 'Requested piece', offeredListing: store.listings.find((item) => item.id === swap.offeredListingId)?.title || 'Offered piece' })); return ok(res, swaps); });
app.post('/api/v1/swaps', auth, swapLimiter, async (req, res) => { const parsed = swapSchema.safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); const store = await readStore(); const requested = store.listings.find((item) => item.id === parsed.data.requestedListingId); const offered = store.listings.find((item) => item.id === parsed.data.offeredListingId); if (!requested || requested.status !== 'available') return error(res, 409, 'This item is no longer available for swap', 'LISTING_UNAVAILABLE'); if (!offered || offered.ownerId !== req.auth.sub) return error(res, 400, 'Choose one of your available pieces to offer', 'INVALID_OFFER'); const swap = { id: nextId('swap'), ...parsed.data, requesterId: req.auth.sub, ownerId: requested.ownerId, status: 'pending', createdAt: new Date().toISOString() }; store.swaps.push(swap); await writeStore(store); return ok(res, swap, 201); });
app.patch('/api/v1/swaps/:id/status', auth, swapLimiter, async (req, res) => { const nextStatus = z.enum(['accepted', 'rejected', 'in_negotiation', 'completed', 'cancelled']).safeParse(req.body.status); if (!nextStatus.success) return error(res, 400, 'Unsupported swap status', 'INVALID_STATUS'); const store = await readStore(); const swap = store.swaps.find((item) => item.id === req.params.id); if (!swap) return error(res, 404, 'Swap request not found', 'SWAP_REQUEST_NOT_FOUND'); if (swap.ownerId !== req.auth.sub && swap.requesterId !== req.auth.sub) return error(res, 403, 'You are not part of this swap', 'FORBIDDEN'); const allowed = { pending: ['accepted', 'rejected', 'cancelled'], accepted: ['in_negotiation', 'completed', 'cancelled'], in_negotiation: ['completed', 'cancelled'] }; if (!allowed[swap.status]?.includes(nextStatus.data)) return error(res, 409, `A ${swap.status} swap cannot become ${nextStatus.data}`, 'INVALID_SWAP_TRANSITION'); swap.status = nextStatus.data; swap.updatedAt = new Date().toISOString(); if (nextStatus.data === 'in_negotiation') swap.agreementConfirmedAt = new Date().toISOString(); await writeStore(store); return ok(res, swap); });
app.patch('/api/v1/swaps/:id/fulfillment', auth, swapLimiter, async (req, res) => { const parsed = z.object({ fulfillmentStatus: z.enum(['not_started', 'arranging', 'in_transit', 'ready_for_exchange', 'received']), trackingReference: z.string().trim().max(120).optional(), handoverLocation: z.string().trim().max(160).optional() }).safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); const store = await readStore(); const swap = store.swaps.find((item) => item.id === req.params.id); if (!swap || (swap.ownerId !== req.auth.sub && swap.requesterId !== req.auth.sub)) return error(res, 403, 'You are not part of this swap', 'FORBIDDEN'); if (!['accepted', 'in_negotiation'].includes(swap.status)) return error(res, 409, 'Confirm the swap agreement before arranging fulfillment', 'SWAP_NOT_READY'); Object.assign(swap, parsed.data, { updatedAt: new Date().toISOString() }); await writeStore(store); return ok(res, swap); });

app.get('/api/v1/swaps/:id/messages', auth, async (req, res) => { const store = await readStore(); const swap = store.swaps.find((item) => item.id === req.params.id); if (!swap || (swap.ownerId !== req.auth.sub && swap.requesterId !== req.auth.sub)) return error(res, 403, 'You are not part of this swap', 'FORBIDDEN'); return ok(res, store.messages.filter((message) => message.swapId === swap.id)); });
app.post('/api/v1/swaps/:id/messages', auth, async (req, res) => { const parsed = messageSchema.safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); const store = await readStore(); const swap = store.swaps.find((item) => item.id === req.params.id); if (!swap || (swap.ownerId !== req.auth.sub && swap.requesterId !== req.auth.sub)) return error(res, 403, 'You are not part of this swap', 'FORBIDDEN'); const message = { id: nextId('message'), swapId: swap.id, senderId: req.auth.sub, content: parsed.data.content, createdAt: new Date().toISOString() }; store.messages.push(message); await writeStore(store); return ok(res, message, 201); });
app.get('/api/v1/swaps/:id/suggestions', auth, async (req, res) => { const store = await readStore(); const swap = store.swaps.find((item) => item.id === req.params.id); if (!swap || (swap.ownerId !== req.auth.sub && swap.requesterId !== req.auth.sub)) return error(res, 403, 'You are not part of this swap', 'FORBIDDEN'); const requested = store.listings.find((item) => item.id === swap.requestedListingId); const offered = store.listings.find((item) => item.id === swap.offeredListingId); return ok(res, { requestedValue: requested?.value || 0, offeredValue: offered?.value || 0, difference: Math.abs((requested?.value || 0) - (offered?.value || 0)), fair: Math.abs((requested?.value || 0) - (offered?.value || 0)) <= 250 }); });
app.post('/api/v1/reports', auth, async (req, res) => { const parsed = reportSchema.safeParse(req.body); if (!parsed.success) return error(res, 400, parsed.error.issues[0].message, 'VALIDATION_ERROR'); const store = await readStore(); const report = { id: nextId('report'), reporterId: req.auth.sub, ...parsed.data, status: 'open', createdAt: new Date().toISOString() }; store.reports.push(report); await writeStore(store); return ok(res, report, 201); });
app.get('/api/v1/admin/users', auth, adminOnly, async (_req, res) => { const store = await readStore(); return ok(res, store.users.map(publicUser)); });
app.get('/api/v1/admin/listings', auth, adminOnly, async (_req, res) => { const store = await readStore(); return ok(res, store.listings); });
app.get('/api/v1/admin/swaps', auth, adminOnly, async (_req, res) => { const store = await readStore(); return ok(res, store.swaps); });
app.get('/api/v1/admin/reports', auth, adminOnly, async (_req, res) => { const store = await readStore(); return ok(res, store.reports || []); });
app.patch('/api/v1/admin/reports/:id', auth, adminOnly, async (req, res) => { const status = z.enum(['open', 'investigating', 'resolved', 'dismissed']).safeParse(req.body.status); if (!status.success) return error(res, 400, 'Unsupported report status', 'INVALID_STATUS'); const store = await readStore(); const report = (store.reports || []).find((item) => item.id === req.params.id); if (!report) return error(res, 404, 'Report not found', 'REPORT_NOT_FOUND'); report.status = status.data; report.resolvedAt = new Date().toISOString(); await writeStore(store); return ok(res, report); });
app.patch('/api/v1/admin/listings/:id/status', auth, adminOnly, async (req, res) => { const status = z.enum(['available', 'hidden', 'removed']).safeParse(req.body.status); if (!status.success) return error(res, 400, 'Unsupported listing status', 'INVALID_STATUS'); const store = await readStore(); const listing = store.listings.find((item) => item.id === req.params.id); if (!listing) return error(res, 404, 'Listing not found', 'LISTING_NOT_FOUND'); listing.status = status.data; await writeStore(store); return ok(res, listing); });
app.get('/api/v1/admin/analytics', auth, adminOnly, async (_req, res) => { const store = await readStore(); const completed = store.swaps.filter((swap) => swap.status === 'completed').length; const activeCutoff = Date.now() - 30 * 24 * 60 * 60 * 1000; const activeUsers = store.users.filter((user) => user.lastActiveAt && new Date(user.lastActiveAt).getTime() >= activeCutoff).length; const totalUsers = store.users.length; const totalListings = store.listings.length; const engagementRate = totalUsers ? Math.round(activeUsers / totalUsers * 100) : 0; const conversionRate = store.swaps.length ? Math.round(completed / store.swaps.length * 100) : 0; return ok(res, { users: totalUsers, activeUsers, engagementRate, totalListings, activeListings: store.listings.filter((item) => item.status === 'available').length, hiddenListings: store.listings.filter((item) => item.status !== 'available').length, totalSwaps: store.swaps.length, successfulSwaps: completed, completedSwaps: completed, swapRequestConversionRate: conversionRate, completionRate: conversionRate, openReports: (store.reports || []).filter((report) => report.status === 'open').length }); });
app.get('/api/v1/admin/overview', auth, adminOnly, async (_req, res) => { const store = await readStore(); return ok(res, { users: store.users.length, listings: store.listings.filter((item) => item.status === 'available').length, swaps: store.swaps.length, openReports: (store.reports || []).filter((report) => report.status === 'open').length }); });
app.use((_req, res) => error(res, 404, 'Route not found', 'NOT_FOUND'));
app.use((err, _req, res, _next) => { console.error(err); return error(res, 500, 'Something went wrong on the server', 'INTERNAL_ERROR'); });
export { app, calculateValue, JWT_SECRET };
